monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:
            error:
                type: rotating_file # Creates a new log file every day.
                path: "%kernel.logs_dir%/%kernel.environment%.error.log"
                level: error
                channels: ["!event"]
                max_files: 30 # Keeps logs for the last 30 days
                formatter: monolog.formatter.json
            warning:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.warning.log"
                level: warning
                channels: [ "!event" ]
                max_files: 30 # Keeps logs for the last 30 days
            info:
                type: rotating_file
                path: '%kernel.logs_dir%/%kernel.environment%.info.log'
                level: info
                max_files: 30
                formatter: monolog.formatter.json
            main:
                type: rotating_file
                path: '%kernel.logs_dir%/%kernel.environment%.log'
                level: debug
                max_files: 30
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json
