<?php

namespace ContainerTTjDzOq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Container_Private_GosWebSocket_Server_EventLoopService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public '.container.private.gos_web_socket.server.event_loop' shared service.
     *
     * @return \React\EventLoop\LoopInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'react'.\DIRECTORY_SEPARATOR.'event-loop'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'LoopInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'react'.\DIRECTORY_SEPARATOR.'event-loop'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Loop.php';

        return $container->services['.container.private.gos_web_socket.server.event_loop'] = \React\EventLoop\Loop::get();
    }
}
