<?php

namespace ContainerTTjDzOq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_GosPubsubRouter_Command_DebugRouter_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.gos_pubsub_router.command.debug_router.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'LazyCommand.php';

        return $container->privates['.gos_pubsub_router.command.debug_router.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('gos:pubsub-router:debug', [], 'Display current routes for a pubsub router', false, #[\Closure(name: 'gos_pubsub_router.command.debug_router', class: 'Gos\\Bundle\\PubSubRouterBundle\\Command\\DebugRouterCommand')] fn (): \Gos\Bundle\PubSubRouterBundle\Command\DebugRouterCommand => ($container->privates['gos_pubsub_router.command.debug_router'] ?? $container->load('getGosPubsubRouter_Command_DebugRouterService')));
    }
}
