<?php

namespace ContainerTTjDzOq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0IoTTi5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0IoTTi5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0IoTTi5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userDto' => ['privates', 'App\\DTOs\\UserDto', 'getUserDtoService', true],
            'validation' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
        ], [
            'userDto' => 'App\\DTOs\\UserDto',
            'validation' => '?',
        ]);
    }
}
