<?php

namespace ContainerTTjDzOq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailNotificationTaskService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\private_lib\listeners\EmailNotificationTask' shared autowired service.
     *
     * @return \App\private_lib\listeners\EmailNotificationTask
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'private_lib'.\DIRECTORY_SEPARATOR.'listeners'.\DIRECTORY_SEPARATOR.'NotificationListener.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'private_lib'.\DIRECTORY_SEPARATOR.'listeners'.\DIRECTORY_SEPARATOR.'EmailNotificationTask.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'mailer'.\DIRECTORY_SEPARATOR.'MailerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'mailer'.\DIRECTORY_SEPARATOR.'Mailer.php';

        $a = ($container->privates['mailer.transports'] ?? $container->load('getMailer_TransportsService'));

        if (isset($container->privates['App\\private_lib\\listeners\\EmailNotificationTask'])) {
            return $container->privates['App\\private_lib\\listeners\\EmailNotificationTask'];
        }
        $b = ($container->services['messenger.default_bus'] ?? self::getMessenger_DefaultBusService($container));

        if (isset($container->privates['App\\private_lib\\listeners\\EmailNotificationTask'])) {
            return $container->privates['App\\private_lib\\listeners\\EmailNotificationTask'];
        }
        $c = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['App\\private_lib\\listeners\\EmailNotificationTask'])) {
            return $container->privates['App\\private_lib\\listeners\\EmailNotificationTask'];
        }

        return $container->privates['App\\private_lib\\listeners\\EmailNotificationTask'] = new \App\private_lib\listeners\EmailNotificationTask(($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), new \Symfony\Component\Mailer\Mailer($a, $b, $c));
    }
}
