<?php

namespace ContainerTTjDzOq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRemovedOldLogFilesJobService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\ScheduleJobs\DeleteFileJob\RemovedOldLogFilesJob' shared autowired service.
     *
     * @return \App\ScheduleJobs\DeleteFileJob\RemovedOldLogFilesJob
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'ScheduleJobs'.\DIRECTORY_SEPARATOR.'DeleteFileJob'.\DIRECTORY_SEPARATOR.'RemovedOldLogFilesJob.php';

        $container->privates['App\\ScheduleJobs\\DeleteFileJob\\RemovedOldLogFilesJob'] = $instance = new \App\ScheduleJobs\DeleteFileJob\RemovedOldLogFilesJob(($container->services['messenger.default_bus'] ?? self::getMessenger_DefaultBusService($container)));

        $instance->setName('app:removed-old-files');
        $instance->setDescription('Delete old log files');

        return $instance;
    }
}
