<?php

namespace ContainerF6BqlAp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A8OuDoRService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.A8OuDoR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A8OuDoR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'taskDto' => ['privates', 'App\\DTOs\\TaskDto', 'getTaskDtoService', true],
            'validator' => ['privates', 'validator', 'getValidatorService', false],
        ], [
            'taskDto' => 'App\\DTOs\\TaskDto',
            'validator' => '?',
        ]);
    }
}
