<?php

namespace ContainerF6BqlAp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.vj2fJ6.', 'get_ServiceLocator_Vj2fJ6_Service', true],
            'App\\Controller\\TaskController::createTask' => ['privates', '.service_locator.A8OuDoR', 'get_ServiceLocator_A8OuDoRService', true],
            'App\\Controller\\UserController::createUser' => ['privates', '.service_locator.0IoTTi5', 'get_ServiceLocator_0IoTTi5Service', true],
            'App\\Controller\\UserController::updateUser' => ['privates', '.service_locator.0IoTTi5', 'get_ServiceLocator_0IoTTi5Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.vj2fJ6.', 'get_ServiceLocator_Vj2fJ6_Service', true],
            'App\\Controller\\TaskController:createTask' => ['privates', '.service_locator.A8OuDoR', 'get_ServiceLocator_A8OuDoRService', true],
            'App\\Controller\\UserController:createUser' => ['privates', '.service_locator.0IoTTi5', 'get_ServiceLocator_0IoTTi5Service', true],
            'App\\Controller\\UserController:updateUser' => ['privates', '.service_locator.0IoTTi5', 'get_ServiceLocator_0IoTTi5Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\TaskController::createTask' => '?',
            'App\\Controller\\UserController::createUser' => '?',
            'App\\Controller\\UserController::updateUser' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\TaskController:createTask' => '?',
            'App\\Controller\\UserController:createUser' => '?',
            'App\\Controller\\UserController:updateUser' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]));
    }
}
