<?php

namespace ContainerF6BqlAp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMigratePasswordsCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\MigratePasswordsCommand' shared autowired service.
     *
     * @return \App\Command\MigratePasswordsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\MigratePasswordsCommand'] = $instance = new \App\Command\MigratePasswordsCommand(($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));

        $instance->setName('app:migrate-passwords');
        $instance->setDescription('Add a short description for your command');

        return $instance;
    }
}
