<?php

namespace ContainerF6BqlAp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRemovingOldLogFilesJob_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\RemovingOldLogFilesJob.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\RemovingOldLogFilesJob.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:delete-old-files', [], 'Delete old log files', false, #[\Closure(name: 'App\\Command\\RemovingOldLogFilesJob')] fn (): \App\Command\RemovingOldLogFilesJob => ($container->privates['App\\Command\\RemovingOldLogFilesJob'] ?? $container->load('getRemovingOldLogFilesJobService')));
    }
}
