<?php

namespace ContainerF6BqlAp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRemovedOldLogFilesJob_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\ScheduleJobs\DeleteFileJob\RemovedOldLogFilesJob.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\ScheduleJobs\\DeleteFileJob\\RemovedOldLogFilesJob.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:removed-old-files', [], 'Delete old log files', false, #[\Closure(name: 'App\\ScheduleJobs\\DeleteFileJob\\RemovedOldLogFilesJob')] fn (): \App\ScheduleJobs\DeleteFileJob\RemovedOldLogFilesJob => ($container->privates['App\\ScheduleJobs\\DeleteFileJob\\RemovedOldLogFilesJob'] ?? $container->load('getRemovedOldLogFilesJobService')));
    }
}
