<?php

namespace ContainerF6BqlAp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRemovedOldLogFilesJobService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\ScheduleJobs\DeleteFileJob\RemovedOldLogFilesJob' shared autowired service.
     *
     * @return \App\ScheduleJobs\DeleteFileJob\RemovedOldLogFilesJob
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\ScheduleJobs\\DeleteFileJob\\RemovedOldLogFilesJob'] = $instance = new \App\ScheduleJobs\DeleteFileJob\RemovedOldLogFilesJob(($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService')));

        $instance->setName('app:removed-old-files');
        $instance->setDescription('Delete old log files');

        return $instance;
    }
}
