<?php

namespace ContainerF6BqlAp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Listener_Login_UserProviderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'security.listener.login.user_provider' shared service.
     *
     * @return \Symfony\Component\Security\Http\EventListener\UserProviderListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['App\\Config\\Security\\UserProvider'] ?? $container->load('getUserProviderService'));

        if (isset($container->privates['security.listener.login.user_provider'])) {
            return $container->privates['security.listener.login.user_provider'];
        }

        return $container->privates['security.listener.login.user_provider'] = new \Symfony\Component\Security\Http\EventListener\UserProviderListener($a);
    }
}
