<?php

namespace ContainerF6BqlAp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Firewall_Authenticator_LoginService extends App_KernelProdContainer
{
    /*
     * Gets the private 'security.firewall.authenticator.login' shared service.
     *
     * @return \Symfony\Component\Security\Http\Firewall\AuthenticatorManagerListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['App\\Config\\Security\\UserAuthenticator'] ?? $container->load('getUserAuthenticatorService'));

        if (isset($container->privates['security.firewall.authenticator.login'])) {
            return $container->privates['security.firewall.authenticator.login'];
        }
        $b = ($container->privates['security.event_dispatcher.login'] ?? $container->load('getSecurity_EventDispatcher_LoginService'));

        if (isset($container->privates['security.firewall.authenticator.login'])) {
            return $container->privates['security.firewall.authenticator.login'];
        }

        return $container->privates['security.firewall.authenticator.login'] = new \Symfony\Component\Security\Http\Firewall\AuthenticatorManagerListener(new \Symfony\Component\Security\Http\Authentication\AuthenticatorManager([$a], ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)), $b, 'login', ($container->privates['monolog.logger.security'] ?? self::getMonolog_Logger_SecurityService($container)), true, true, []));
    }
}
