<?php

namespace ContainerF6BqlAp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaskDtoResolverService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\DTOResolvers\TaskDtoResolver' shared autowired service.
     *
     * @return \App\DTOResolvers\TaskDtoResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\DTOResolvers\\TaskDtoResolver'] = new \App\DTOResolvers\TaskDtoResolver(($container->privates['serializer'] ?? self::getSerializerService($container)));
    }
}
