<?php

namespace ContainerF6BqlAp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTurbo_Mercure_Default_BroadcasterService extends App_KernelProdContainer
{
    /*
     * Gets the private 'turbo.mercure.default.broadcaster' shared service.
     *
     * @return \Symfony\UX\Turbo\Bridge\Mercure\Broadcaster
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['turbo.mercure.default.broadcaster'] = new \Symfony\UX\Turbo\Bridge\Mercure\Broadcaster('default', ($container->privates['mercure.hub.default'] ?? $container->load('getMercure_Hub_DefaultService')));
    }
}
