<?php

namespace ContainerF6BqlAp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserServiceImplService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\Impl\UserServiceImpl' shared autowired service.
     *
     * @return \App\Service\Impl\UserServiceImpl
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\Impl\\UserServiceImpl'] = new \App\Service\Impl\UserServiceImpl(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')));
    }
}
