<?php

namespace ContainerF6BqlAp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserDtoResolverService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\DTOResolvers\UserDtoResolver' shared autowired service.
     *
     * @return \App\DTOResolvers\UserDtoResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\DTOResolvers\\UserDtoResolver'] = new \App\DTOResolvers\UserDtoResolver(($container->privates['serializer'] ?? self::getSerializerService($container)));
    }
}
