<?php

namespace ContainerF6BqlAp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getViberNotificationTaskService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\private_lib\listeners\ViberNotificationTask' shared autowired service.
     *
     * @return \App\private_lib\listeners\ViberNotificationTask
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\private_lib\\listeners\\ViberNotificationTask'] = new \App\private_lib\listeners\ViberNotificationTask(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
