controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: annotation

api_login:
    path: /api/login
    controller: App\Controller\SecurityController::login
    methods: [POST]
