<?php

namespace ContainerYX0Sypr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Container_Private_GosWebSocket_Dispatcher_TopicService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public '.container.private.gos_web_socket.dispatcher.topic' shared service.
     *
     * @return \Gos\Bundle\WebSocketBundle\Server\App\Dispatcher\TopicDispatcher
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'gos'.\DIRECTORY_SEPARATOR.'web-socket-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Server'.\DIRECTORY_SEPARATOR.'App'.\DIRECTORY_SEPARATOR.'Dispatcher'.\DIRECTORY_SEPARATOR.'TopicDispatcherInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'gos'.\DIRECTORY_SEPARATOR.'web-socket-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Server'.\DIRECTORY_SEPARATOR.'App'.\DIRECTORY_SEPARATOR.'Dispatcher'.\DIRECTORY_SEPARATOR.'TopicDispatcher.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'gos'.\DIRECTORY_SEPARATOR.'web-socket-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Server'.\DIRECTORY_SEPARATOR.'App'.\DIRECTORY_SEPARATOR.'Registry'.\DIRECTORY_SEPARATOR.'TopicRegistry.php';

        $a = ($container->services['.container.private.gos_web_socket.wamp.topic_manager'] ?? $container->load('get_Container_Private_GosWebSocket_Wamp_TopicManagerService'));

        if (isset($container->services['.container.private.gos_web_socket.dispatcher.topic'])) {
            return $container->services['.container.private.gos_web_socket.dispatcher.topic'];
        }

        $container->services['.container.private.gos_web_socket.dispatcher.topic'] = $instance = new \Gos\Bundle\WebSocketBundle\Server\App\Dispatcher\TopicDispatcher(($container->services['.container.private.gos_web_socket.registry.topic'] ??= new \Gos\Bundle\WebSocketBundle\Server\App\Registry\TopicRegistry()), ($container->services['.container.private.gos_web_socket.topic.periodic_timer'] ?? $container->load('get_Container_Private_GosWebSocket_Topic_PeriodicTimerService')), $a);

        $instance->setLogger(($container->privates['monolog.logger.websocket'] ?? $container->load('getMonolog_Logger_WebsocketService')));

        return $instance;
    }
}
