<?php

namespace ContainerYX0Sypr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCacheServiceImplService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Impl\CacheServiceImpl' shared autowired service.
     *
     * @return \App\Service\Impl\CacheServiceImpl
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'CacheService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Impl'.\DIRECTORY_SEPARATOR.'CacheServiceImpl.php';

        return $container->privates['App\\Service\\Impl\\CacheServiceImpl'] = new \App\Service\Impl\CacheServiceImpl(($container->privates['snc_redis.default'] ?? $container->load('getSncRedis_DefaultService')));
    }
}
