<?php

namespace ContainerYX0Sypr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGosPubsubRouter_Command_DebugRouterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'gos_pubsub_router.command.debug_router' shared service.
     *
     * @return \Gos\Bundle\PubSubRouterBundle\Command\DebugRouterCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'gos'.\DIRECTORY_SEPARATOR.'pubsub-router-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'DebugRouterCommand.php';

        $container->privates['gos_pubsub_router.command.debug_router'] = $instance = new \Gos\Bundle\PubSubRouterBundle\Command\DebugRouterCommand(($container->services['.container.private.gos_pubsub_router.router_registry'] ?? $container->load('get_Container_Private_GosPubsubRouter_RouterRegistryService')));

        $instance->setName('gos:pubsub-router:debug');
        $instance->setDescription('Display current routes for a pubsub router');

        return $instance;
    }
}
