<?php

namespace ContainerYX0Sypr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSncRedis_DefaultService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'snc_redis.default' shared service.
     *
     * @return \Redis
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->privates['snc_redis.default'] = $container->createProxy('RedisProxy4df9f64', static fn () => \RedisProxy4df9f64::createLazyProxy(static fn () => self::do($container, false)));
        }

        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'snc'.\DIRECTORY_SEPARATOR.'redis-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Factory'.\DIRECTORY_SEPARATOR.'PhpredisClientFactory.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'snc'.\DIRECTORY_SEPARATOR.'redis-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Logger'.\DIRECTORY_SEPARATOR.'RedisCallInterceptor.php';

        return (new \Snc\RedisBundle\Factory\PhpredisClientFactory(new \Snc\RedisBundle\Logger\RedisCallInterceptor(($container->privates['snc_redis.logger'] ?? self::getSncRedis_LoggerService($container)), ($container->services['debug.stopwatch'] ??= new \Symfony\Component\Stopwatch\Stopwatch(true))), NULL))->create('Redis', [$container->getEnv('REDIS_URL')], ['connection_async' => false, 'connection_persistent' => false, 'connection_timeout' => 5, 'read_write_timeout' => NULL, 'iterable_multibulk' => false, 'throw_errors' => true, 'serialization' => 'default', 'cluster' => NULL, 'prefix' => NULL, 'service' => NULL], 'default', false);
    }
}
