<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYX0Sypr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYX0Sypr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYX0Sypr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYX0Sypr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYX0Sypr\App_KernelDevDebugContainer([
    'container.build_hash' => 'YX0Sypr',
    'container.build_id' => 'd66d899d',
    'container.build_time' => 1740639620,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYX0Sypr');
