<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTTjDzOq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTTjDzOq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTTjDzOq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTTjDzOq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTTjDzOq\App_KernelDevDebugContainer([
    'container.build_hash' => 'TTjDzOq',
    'container.build_id' => '883c1ae1',
    'container.build_time' => 1740610647,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTTjDzOq');
